const productList = [
    {
        id: "67a1f4e43f34a77c6dde7144",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "Mens Blue Shirt",
        description: "This blue check shirt blends classic style with modern comfort. Made from 100% breathable cotton, it's perfect for both casual and semi-formal occasions. The fine check pattern adds a timeless appeal, while the slim-fit design ensures a tailored look. Pair it with jeans or chinos for a versatile outfit choice. Machine washable for easy care.",
        price: 499.00,
        offprice: 399.99,
        img: [
            "/img/vecteezy_classic-blue-plaid-shirt-for-men_57930719.png",
            "/img/—Pngtree—classic red and black plaid_20698608.png",
            "/img/—Pngtree—plaid shirt with a bold_18559440.png",
        ],
        brand: "Celvin kein",
        color: "red black gray",
        category: "men's clothing Outfit  dress  top shirt boy",
        date: 1738667236865,
        count: 1,
        ratings: "(4.0) ★★★★",
        noratings: "★",
    },
    {
        id: "67a1f4e43f34a77b6ede7144",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "Black Cap",
        description: "Discover a wide range of stylish and comfortable caps perfect for every season. Whether you’re shielding from the sun or making a fashion statement, our caps combine functionality with trend-setting designs. Choose from snapbacks, baseball caps, and more to match your look. Upgrade your wardrobe with the perfect cap today!.",
        price: 199.00,
        offprice: 399.99,
        img: [
            "/img/cap1.png",
            "/img/vecteezy_stylish-gray-cap-with-curved-brim-perfect-for-casual-wear_52783248.png",
            "/img/vecteezy_stylish-brown-baseball-cap-made-from-durable-fabric-perfect_52783239.png",
            "/img/vecteezy_stylish-blue-cap-made-of-durable-fabric-perfect-for-casual_52783215.png",
        ],
        brand: "Nike",
        color: "red orange gray brown",
        category: "men's clothing Outfit  dress  top shirt boy",
        date: 1738667236865,
        count: 1,
        ratings: "(3.0) ★★★",
        noratings: "★★",
    },

    {
        id: "67a1f4e43s34a77b6dde7144",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "Women's top",
        description: "A blouse is a versatile and stylish upper garment, perfect for both casual and formal wear. Available in various fabrics like cotton, silk, and chiffon, it complements sarees, skirts, or jeans effortlessly. Look for designs with embroidery, prints, or lace detailing to add elegance to your outfit. Choose a well-fitted blouse to enhance comfort and style.",
        price: 599.00,
        offprice: 399.99,
        img: [
            "/img/vecteezy_elegant-women-s-blue-blouse-with-big-bow-and-puff-sleeves_59046640.png",
            "/img/vecteezy_elegant-womens-white-long-sleeve-blouse-with-big-bow_59046585.png",
            "/img/vecteezy_elegant-black-and-red-women-s-blouse-with-pleated-skirt-and-bow_59046472.png",
        ],
        brand: "Gucci",
        color: "red black white",
        category: "women's clothing Outfit  dress  top shirt girl",
        date: 1738667236865,
        count: 1,
        ratings: "(4.5) ★★★★",
        noratings: "★",
    },

    {
        id: "67a1f4e43f34a77b6dde7144",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "Apple AirPods Pro 2nd gen",
        description: "Apple AirPods Pro (2nd Gen) with MagSafe Case (USB-C) provide excellent sound, active noise cancellation, and a comfortable fit. The USB-C case ensures quick charging, and they pair seamlessly with Apple devices for an effortless audio experience.",
        price: 5499.00,
        offprice: 399.99,
        img: [
            "/img/apple_earphone_image.png",
            "/img/vecteezy_white-earbuds-in-transparent-background-side-view_46787021.png",
            "/img/vecteezy_white-wireless-earbuds-isolated_49216182.png",
        ],
        brand: "Apple",
        color: "white",
        category: "Earphone headphone",
        date: 1738667236865,
        count: 1,
        ratings: "(4.5) ★★★★",
        noratings: "★",
    },
    // {
    //     id: "67a1f4e43f34a77b6dde9144",
    //     userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
    //     name: "Apple AirPods Pro 2nd gen",
    //     description: "Apple AirPods Pro (2nd Gen) with MagSafe Case (USB-C) provide excellent sound, active noise cancellation, and a comfortable fit. The USB-C case ensures quick charging, and they pair seamlessly with Apple devices for an effortless audio experience.",
    //     price: 499.99,
    //     offprice: 399.99,
    //     img: [
    // "https://raw.githubusercontent.com/avinashdm/gs-images/main/quickcart/k4dafzhwhgcn5tnoylrw.webp",
    // "https://raw.githubusercontent.com/avinashdm/gs-images/main/quickcart/j212frakb8hdrhvhajhg.webp",
    // "https://raw.githubusercontent.com/avinashdm/gs-images/main/quickcart/imwuugqxsajuwqpkegb5.webp",
    // "https://raw.githubusercontent.com/avinashdm/gs-images/main/quickcart/k1oqaslw5tb3ebw01vvj.webp"
    //     ],
    //     category: "Earphone",
    //     date: 1738667236865,
    //     count: 1,
    // },
    {
        id: "67a1f52e3f34a77b6dde914a",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "Bose QuietComfort 45",
        description: "The Bose QuietComfort 45 headphones are engineered for exceptional sound quality and unparalleled noise cancellation. With a 24-hour battery life and comfortable, lightweight design, these headphones deliver premium audio for any environment. Whether on a flight, in the office, or at home, the Bose QC45 blocks out distractions, offering an immersive listening experience.",
        price: 999.00,
        offprice: 329.99,
        img: [
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/quickcart/m16coelz8ivkk9f0nwrz.webp",
        ],
        brand: "Bose",
        color: "black",
        category: "Earphone headphone",
        date: 1738667310300,
        count: 1,
        ratings: "(4.0) ★★★★",
        noratings: "★",
    },
    {
        id: "67a1f5663f34a77b6dde914c",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "Samsung Galaxy S23",
        description: "The Samsung Galaxy S23 offers an all-encompassing mobile experience with its advanced AMOLED display, offering vibrant visuals and smooth interactions. Equipped with top-of-the-line fitness tracking features and cutting-edge technology, this phone delivers outstanding performance. With powerful hardware, a sleek design, and long battery life, the S23 is perfect for those who demand the best in mobile innovation.",
        price: 49999.00,
        offprice: 799.99,
        img: [
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/quickcart/xjd4eprpwqs7odbera1w.webp",
            "/img/vecteezy_samsung-galaxy-a25-personality-yellow_41329787.png",
        ],
        brand: "Samsung",
        color: "lightpurple yellow",
        category: "Smartphone",
        date: 1738667366224,
        count: 1,
        ratings: "(4.5) ★★★★",
        noratings: "★",
    },
    {
        id: "67a1f5993f34a77b6dde914e",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "Garmin Venu 2",
        description: "The Garmin Venu 2 smartwatch blends advanced fitness tracking with sophisticated design, offering a wealth of features such as heart rate monitoring, GPS, and sleep tracking. Built with a 24-hour battery life, this watch is ideal for fitness enthusiasts and anyone looking to enhance their daily lifestyle. With a stunning AMOLED display and customizable watch faces, the Venu 2 combines technology with style seamlessly.",
        price: 399.00,
        offprice: 349.99,
        img: [
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/quickcart/hdfi4u3fmprazpnrnaga.webp"
        ],
        brand: "Garmin",
        color: "black",
        category: "Earphone headphone",
        date: 1738667417511,
        count: 1,
        ratings: "(4.0) ★★★★",
        noratings: "★",
    },
    {
        id: "67a1f5ef3f34a77b6dde9150",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "PlayStation 5",
        description: "The PlayStation 5 takes gaming to the next level with ultra-HD graphics, a powerful 825GB SSD, and ray tracing technology for realistic visuals. Whether you're into high-action games or immersive storytelling, the PS5 delivers fast loading times, seamless gameplay, and stunning visuals. It's a must-have for any serious gamer looking for the ultimate gaming experience.",
        price: 699.00,
        offprice: 499.99,
        brand: "Asus",
        color: "blue",
        img: [
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/quickcart/dd3l13vfoartrgbvkkh5.webp"
        ],
        category: "Accessories",
        date: 1738667503075,
        count: 1,
        ratings: "(4.0) ★★★★",
        noratings: "★",
    },
    {
        id: "67a1f70c3f34a77b6dde9156",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "Canon EOS R5",
        description: "The Canon EOS R5 is a game-changing mirrorless camera with a 45MP full-frame sensor, offering ultra-high resolution and the ability to shoot 8K video. Whether you're capturing professional-quality stills or cinematic video footage, this camera delivers exceptional clarity, speed, and color accuracy. With advanced autofocus and in-body stabilization, the R5 is ideal for photographers and videographers alike.",
        price: 4199.00,
        offprice: 3899.99,
        img: [
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/quickcart/r5h370zuujvrw461c6wy.webp"
        ],
        brand: "Bose",
        color: "black",
        category: "Camera",
        date: 1738667788883,
        count: 1,
        ratings: "(4.5) ★★★★",
        noratings: "★",
    },
    {
        id: "67a1f7c93f34a77b6dde915a",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "MacBook Pro 16",
        description: "The MacBook Pro 16, powered by Apple's M2 Pro chip, offers outstanding performance with 16GB RAM and a 512GB SSD. Whether you're editing high-resolution video, developing software, or multitasking with ease, this laptop can handle the toughest tasks. It features a stunning Retina display with True Tone technology, making it a top choice for professionals in creative industries or anyone who demands premium performance in a portable form.",
        price: 59999.00,
        offprice: 2499.99,
        img: [
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/quickcart/rzri7kytphxalrm9rubd.webp"
        ],
        brand: "Apple",
        color: "White",
        category: "Laptop  mackbook",
        date: 1738667977644,
        count: 1,
        ratings: "(4.7) ★★★★",
        noratings: "★",
    },
    {
        id: "67a1f8363f34a77b6dde915c",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "Sony WF-1000XM5",
        description: "Sony WF-1000XM5 true wireless earbuds deliver immersive sound with Hi-Res Audio and advanced noise cancellation technology. Designed for comfort and quality, they provide a stable, snug fit for a secure listening experience. Whether you're working out or traveling, these earbuds will keep you connected with the world around you while enjoying rich, clear sound.",
        price: 699.00,
        offprice: 299.99,
        img: [
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/quickcart/e3zjaupyumdkladmytke.webp"
        ],
        brand: "Sony",
        color: "black",
        category: "Earphone headphone",
        date: 1738668086331,
        count: 1,
        ratings: "(4.0) ★★★★",
        noratings: "★",
    },
    {
        id: "67a1f85e3f34a77b6dde915e",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "Samsung Projector 4k",
        description: "The Samsung 4K Projector offers an immersive cinematic experience with ultra-high-definition visuals and realistic color accuracy. Equipped with a built-in speaker, it delivers rich sound quality to complement its stunning 4K resolution. Perfect for movie nights, gaming, or presentations, this projector is the ultimate choice for creating an at-home theater experience or professional setting.",
        price: 1699.99,
        offprice: 1499.99,
        img: [
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/quickcart/qqdcly8a8vkyciy9g0bw.webp"
        ],
        brand: "Samsung",
        color: "white",
        category: "Accessories",
        date: 1738668126660,
        count: 1,
        ratings: "(4.0) ★★★★",
        noratings: "★",
    },
    {
        id: "67a1fa4b3f34a77b6dde9166",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "ASUS ROG Zephyrus G16",
        description: "The ASUS ROG Zephyrus G16 gaming laptop is powered by the Intel Core i9 processor and features an RTX 4070 GPU, delivering top-tier gaming and performance. With 16GB of RAM and a 1TB SSD, this laptop is designed for gamers who demand extreme power, speed, and storage. Equipped with a stunning 16-inch display, it's built to handle the most demanding titles and applications with ease.",
        price: 79000.00,
        offprice: 1999.99,
        img: [
            "https://raw.githubusercontent.com/avinashdm/gs-images/main/quickcart/wig1urqgnkeyp4t2rtso.webp"
        ],
        brand: "Asus",
        color: "black",
        category: "Laptop  mackbook",
        date: 1738668619198,
        ratings: "(4.9) ★★★★",
        noratings: "★",
        count: 1,
    },

    {
        id: "67a1fa4b3f34a77b6dde9176",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "Samsung S24 Ultra",
        description: "The Samsung Galaxy S24 Ultra is a flagship smartphone featuring a 6.8-inch Dynamic AMOLED 2X display with a 120Hz refresh rate, delivering stunning clarity and smooth visuals. Powered by the Snapdragon 8 Gen 2 processor, it ensures fast performance and excellent gaming capabilities. Its 200MP main camera captures incredibly detailed photos, and the large 5000mAh battery offers long-lasting power for heavy use.",
        price: 79000.00,
        offprice: 1999.99,
        img: [
            "/img/vecteezy_samsung-galaxy-s23-ultra-transparent-image_22722945.png"
        ],
        brand: "Samsung",
        color: "gray",
        category: "smartphone",
        date: 1738668619198,
        count: 1,
        ratings: "(4.9) ★★★★",
        noratings: "★",
        count: 1,
    },
    {
        id: "67a1fa4b3f34a77b6dde9136",
        userid: "user_2sZFHS1UIIysJyDVzCpQhUhTIhw",
        name: "Auxi headphone bass boost",
        description: "Auxi Headphones with bass boost are designed to enhance low-frequency sounds, giving music deeper and more powerful beats for an immersive listening experience. They often feature tuned drivers or built-in equalizers that emphasize bass without distorting vocals or treble. Ideal for genres like EDM, hip-hop, or gaming, these headphones deliver punchy, rich bass for a more impactful sound.",
        price: 2999.00,
        offprice: 1999.99,
        img: [
            "/img/header_headphone_image.png"
        ],
        brand: "Auxi",
        color: "black",
        category: "Earphone headphone",
        date: 1738668619198,
        count: 1,
        ratings: "(4.9) ★★★★",
        noratings: "★",
        count: 1,
    },
    {
        id: "67a1fa4b3f34a77b6dde9135",
        name: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
        price: 500,
        description: "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
        category: "men's clothing Outfit  dress  top shirt",
        img: ["https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png"],
        ratings: "(3.0) ★★★",
        noratings: "★★",
        count: 1,
    },
    {
        id: "67a1fa4b3f34a77b6dhe9136",
        name: "Mens Casual Premium Slim Fit T-Shirts ",
        price: 500,
        description: "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
        category: "men's clothing Outfit  dress  top shirt boy",
        img: ["https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png"],
        ratings: "(4.9) ★★★★",
        noratings: "★",
        count: 1,
    },
    {
        id: "67a1fd4b3f34a77b6dde9136",
        name: "Mens Cotton Jacket",
        price: 1200,
        description: "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
        category: "men's clothing Outfit  dress  top shirt boy",
        img: ["https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png"],
        ratings: "(4.9) ★★★★",
        noratings: "★",
        count: 1,
    },
    {
        id: "67a1fa4b3fr4a77b6dde9136",
        name: "Mens Casual Slim Fit",
        price: 600,
        description: "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
        category: "men's clothing Outfit  dress  top shirt boy",
        img: ["https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_t.png"],
        ratings: "(4.9) ★★★★",
        noratings: "★",
        count: 1,
    },
    {
        id: "67a5fa4b3f34a77b6dde9136",
        name: "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
        price: 900,
        description: "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
        category: "jewelery gold silver girl",
        img: ["https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png"],
        ratings: "(4.9) ★★★★",
        noratings: "★",
        count: 1,
    },
    {
        id: "87a1fa4b3f34a77b6dde9136",
        name: "Solid Gold Petite Micropave ",
        price: 6000,
        description: "Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.",
        category: "jewelery gold silver girl",
        img: ["https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_t.png"],
        ratings: "(4.9) ★★★★",
        noratings: "★",
        count: 1,
    },
    {
        id: "67a1ga4b3f34a77b6dde9136",
        name: "White Gold Plated Princess",
        price: 5000,
        description: "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
        category: "jewelery gold silver girl",
        img: ["https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_t.png"],
        ratings: "(4.9) ★★★★",
        noratings: "★",
        count: 1,
    },
    {
        id: "67a1fafb3f34a77b6dde9136",
        name: "Pierced Owl Rose Gold Plated Stainless Steel Double",
        price: 1500,
        description: "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
        category: "jewelery gold silver girl",
        img: ["https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_t.png"],
        ratings: "(4.9) ★★★★",
        noratings: "★",
        count: 1,
    },
    {
        id: "67a1fa4b3f34g77b6dde9136",
        name: "WD 2TB Elements Portable External Hard Drive - USB 3.0 ",
        price: 1000,
        description: "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system",
        category: "electronics drive",
        img: ["https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png"],
        ratings: "(3.0) ★★★",
        noratings: "★★",
        count: 1,
    },
    {
        id: "67a1fa4bd3f34a77b6dde9136",
        name: "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
        price: 2000,
        description: "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
        category: "electronics drive",
        img: ["https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png"],
        ratings: "(3.0) ★★★",
        noratings: "★★",
        count: 1,
    },
    {
        id: "67a1fa4b3g34a77b6dde9136",
        name: "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
        price: 700,
        description: "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
        category: "electronics drive",
        img: ["https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_t.png"],
        ratings: "(3.0) ★★★",
        noratings: "★★",
        count: 1,
    },
    {
        id: "67a1fl4b3f34a77b6dde9136",
        name: "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
        price: 5000,
        description: "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
        category: "electronics drive",
        img: ["https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png"],
        ratings: "(3.0) ★★★",
        noratings: "★★",
        count: 1,
    },
    {
        id: "67a1fa4b3f34a77b6dde913v",
        name: "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin",
        price: 40000,
        description: "21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz",
        category: "electronics tv lcd",
        img: ["https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png"],
        ratings: "(4.9) ★★★★",
        noratings: "★",
        count: 1,
    },
    {
        id: "67a1fa4b3f34a77b6dde9136b",
        name: "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ",
        price: 60000,
        description: "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag",
        category: "electronics tv lcd",
        img: ["https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png"],
        ratings: "(4.9) ★★★★",
        noratings: "★",
        count: 1,
    },
    {
        id: "67a1fa4b3f34a77b6dde913x",
        name: "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
        price: 700,
        description: "Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates",
        category: "women's clothing Outfit  dress  top shirt girl",
        img: ["https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_t.png"],
        ratings: "(3.0) ★★★",
        noratings: "★★",
    },
    {
        id: "67a1fa4b3f34a77b6dde913m",
        name: "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
        price: 1000,
        description: "100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON",
        category: "women's clothing Outfit  dress  top shirt girl",
        img: ["https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_t.png"],
        ratings: "(4.9) ★★★★",
        noratings: "★",
        count: 1,
    },
    {
        id: "67a1fa4b3f34a77b6dde913n",
        name: "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
        price: 500,
        description: "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
        category: "women's clothing Outfit  dress  top shirt girl",
        img: ["https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2t.png"],
        ratings: "(3.0) ★★★",
        noratings: "★★",
        count: 1,
    },
    {
        id: "67a1fa4b3f34as7b6dde9136",
        name: "MBJ Women's Solid Short Sleeve Boat Neck V ",
        price: 400,
        description: "95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem",
        category: "women's clothing Outfit  dress  top shirt girl",
        img: ["https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_t.png"],
        ratings: "(3.0) ★★★",
        noratings: "★★",
        count: 1,
    },
    {
        id: "67a1fa4b3f34a77i6dde9136",
        name: "Opna Women's Short Sleeve Moisture",
        price: 600,
        description: "100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
        category: "women's clothing Outfit  dress  top shirt girl",
        img: ["https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_t.png"],
        ratings: "(3.0) ★★★",
        noratings: "★★",
        count: 1,
    },
    {
        id: "67a1fa4q3f34a77b6dde9136",
        name: "DANVOUY Womens T Shirt Casual Cotton Short",
        price: 600,
        description: "95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.",
        category: "women's clothing Outfit  dress  top shirt girl",
        img: ["https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_t.png"],
        ratings: "(3.0) ★★★",
        noratings: "★★",
        count: 1,
    },
]

export default productList